# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2023 Ilia Sotnikov
---
packages:
  substitutions: !include substitutions.yaml
  version: !include version.yaml
  outputs: !include outputs.yaml
  controllers: !include controllers.yaml
  status_sensors: !include status_sensors.yaml
  schedule: !include schedule.yaml  # Optional
  time: !include time.yaml  # Optional

# 2025.7.0 introduced change from `publish_initial_state` to
# `trigger_on_initial_state` for `binary_sensor` component
esphome:
  min_version: '2025.7.0'
