# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2023 Ilia Sotnikov
---
substitutions:
  base_path: .
  run_duration_uom: s
  run_duration_initial_value: '5'
  refill_tank_relay_id: relay_7
  pump_relay_id: relay_8
  valve_overlap: 1s
  pump_start_pump_delay: 1s
  pump_stop_valve_delay: 1s
  led_id: led
  display_backlight_id: display1_backlight
  display_page_when_active: display_page1

packages:
  outputs: !include outputs.yaml
  inputs: !include inputs.yaml
  schedule: !include schedule.yaml
  display: !include display.yaml
  indicators: !include indicators.yaml
  controllers: !include controllers.yaml
  status_sensors: !include status_sensors.yaml
  time: !include time.yaml
