# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2023 Ilia Sotnikov
---
switch:
  # Schedule, lawn sprinklers
  - platform: template
    id: lawn_sprinklers_mon
    name: "Lawn sprinklers: Mon"
    optimistic: true
    restore_state: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
  - platform: template
    id: lawn_sprinklers_tue
    name: "Lawn sprinklers: Tue"
    optimistic: true
    restore_state: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
  - platform: template
    id: lawn_sprinklers_wed
    name: "Lawn sprinklers: Wed"
    optimistic: true
    restore_state: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
  - platform: template
    id: lawn_sprinklers_thu
    name: "Lawn sprinklers: Thu"
    optimistic: true
    restore_state: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
  - platform: template
    id: lawn_sprinklers_fri
    name: "Lawn sprinklers: Fri"
    optimistic: true
    restore_state: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
  - platform: template
    id: lawn_sprinklers_sat
    name: "Lawn sprinklers: Sat"
    optimistic: true
    restore_state: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
  - platform: template
    id: lawn_sprinklers_sun
    name: "Lawn sprinklers: Sun"
    optimistic: true
    restore_state: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config

  # Schedule, flowerbed sprinklers
  - platform: template
    id: flowerbed_sprinklers_mon
    name: "Flowerbed sprinklers: Mon"
    optimistic: true
    restore_state: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
  - platform: template
    id: flowerbed_sprinklers_tue
    name: "Flowerbed sprinklers: Tue"
    optimistic: true
    restore_state: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
  - platform: template
    id: flowerbed_sprinklers_wed
    name: "Flowerbed sprinklers: Wed"
    optimistic: true
    restore_state: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
  - platform: template
    id: flowerbed_sprinklers_thu
    name: "Flowerbed sprinklers: Thu"
    optimistic: true
    restore_state: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
  - platform: template
    id: flowerbed_sprinklers_fri
    name: "Flowerbed sprinklers: Fri"
    optimistic: true
    restore_state: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
  - platform: template
    id: flowerbed_sprinklers_sat
    name: "Flowerbed sprinklers: Sat"
    optimistic: true
    restore_state: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
  - platform: template
    id: flowerbed_sprinklers_sun
    name: "Flowerbed sprinklers: Sun"
    optimistic: true
    restore_state: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config

number:
  # Schedule, lawn sprinklers
  - platform: template
    id: lawn_sprinklers_hour
    name: "Lawn sprinklers: Hour"
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 0
    min_value: 0
    max_value: 24
    step: 1
    mode: box
  - platform: template
    name: "Lawn sprinklers: Minute"
    id: lawn_sprinklers_minute
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 0
    min_value: 0
    max_value: 59
    step: 1
    mode: box

  # Schedule, flowerbed sprinklers
  - platform: template
    name: "Flowerbed sprinklers: Hour"
    id: flowerbed_sprinklers_hour
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 0
    min_value: 0
    max_value: 24
    step: 1
    mode: box
  - platform: template
    name: "Flowerbed sprinklers: Minute"
    id: flowerbed_sprinklers_minute
    entity_category: config
    optimistic: true
    restore_value: true
    initial_value: 0
    min_value: 0
    max_value: 59
    step: 1
    mode: box

# Dynamic time.on_time component
esphome:
  includes:
    - ${base_path}/dynamic_on_time.h

custom_component:
  - lambda: |-
      auto lawn_sprinklers_on_time = new DynamicOnTime(
        "lawn_sprinklers_on_time",
        homeassistant_time,
        lawn_sprinklers_hour,
        lawn_sprinklers_minute,
        lawn_sprinklers_mon,
        lawn_sprinklers_tue,
        lawn_sprinklers_wed,
        lawn_sprinklers_thu,
        lawn_sprinklers_fri,
        lawn_sprinklers_sat,
        lawn_sprinklers_sun,
        new sprinkler::StartFullCycleAction<>(lawn_sprinklers)
      );
      auto flowerbed_sprinklers_on_time = new DynamicOnTime(
        "flowerbed_sprinklers_on_time",
        homeassistant_time,
        flowerbed_sprinklers_hour,
        flowerbed_sprinklers_minute,
        flowerbed_sprinklers_mon,
        flowerbed_sprinklers_tue,
        flowerbed_sprinklers_wed,
        flowerbed_sprinklers_thu,
        flowerbed_sprinklers_fri,
        flowerbed_sprinklers_sat,
        flowerbed_sprinklers_sun,
        new sprinkler::StartFullCycleAction<>(flowerbed_sprinklers)
      );

      return {
        lawn_sprinklers_on_time,
        flowerbed_sprinklers_on_time
      };
    components:
      - id: lawn_sprinklers_on_time
      - id: flowerbed_sprinklers_on_time
