# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2023 Ilia Sotnikov
---
sensor:
  - platform: internal_temperature
    id: temperature
    name: "Internal Temperature"
    entity_category: diagnostic
    update_interval: 60s

text_sensor:
  - platform: template
    id: lawn_sprinklers_state
    name: "Lawn sprinklers state"
    entity_category: diagnostic
    lambda: !include
      file: script_controller_status.yaml
      vars:
        sprinkler: lawn_sprinklers
    update_interval: 5s
  - platform: template
    id: flowerbed_sprinklers_state
    entity_category: diagnostic
    name: "Flowerbed sprinklers state"
    lambda: !include
      file: script_controller_status.yaml
      vars:
        sprinkler: flowerbed_sprinklers
    update_interval: 5s
  - platform: template
    entity_category: diagnostic
    id: pump_state
    name: "Pump state"
    update_interval: 5s
    lambda: |-
      return { ${pump_relay_id}->state ? "Active" : "Idle" };
  - platform: template
    entity_category: diagnostic
    id: tank_refill_state
    name: "Tank refill state"
    update_interval: 5s
    lambda: |-
      return { ${refill_tank_relay_id}->state ? "Active" : "Idle" };
